### ISSUE TITLE
Indicate when booting

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_motd#31]
If the MOTD gets printed to early, the number of applications running won't be the full amount. For example:

```
Applications : 12 / 13 (nerves_pack not started)
```

This looks like it might be bad, but it really isn't. It would be nice if this wouldn't show up as red and be labeled to tell the user that the system is booting. Perhaps make it yellow and change it to be `12 / 13 (starting up)`.

**Comment by danielzfranklin** [comment]
When I saw this I also expected the denominator to be correct, but when I ran `NervesMOTD.print` later I saw `Applications : 83 / 83`. Maybe it should just say `12 loaded so far` if the denominator isn't meaningful?

**Comment by fhunleth** [comment]
Good point on the denominator. I agree that it shouldn't be printed on boot since it's not accurate then.
