### ISSUE TITLE
Nerves logo doesn't render correctly on attached displays

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_motd#32]
Here's an example of it rendering incorrectly on a Raspberry Pi 7" Touchscreen:

![image](https://user-images.githubusercontent.com/64669/136676306-a2e1ae7d-7096-4450-a5e7-e56e0ed3f6a2.png)

I think this is the font that's being used to render the logo: https://elixir.bootlin.com/linux/latest/source/lib/fonts/font_8x16.c.

**Comment by fhunleth** [comment]
I looked into this a little more. The font that's being used only supports 8-bit characters, so only `█ ▀ ▄ ▌▐` are available. That's a full block, then top half, bottom half, left half and right half. The Nerves logo uses quarter blocks and L shaped blocks as well, and it looks like it tries to map them to the support half block characters.

I don't think it's possible to detect whether the font used for the terminal includes the Unicode quarter block characters. I think the only thing to do is to try to update the Nerves logo to pick from the supported set. I'm not sure how hard that will be.

**Comment by fhunleth** [comment]
Attempt 1. I took your latest and tried to make it more symmetric:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/64669/137585111-2e6109b9-6bc5-4bbc-b152-19d45435891d.png">

```
  @logo """
  \e[34m████▄▄    \e[36m▐███
  \e[34m█▌  ▀▀██▄▄  \e[36m▐█
  \e[34m█▌  \e[36m▄▄  \e[34m▀▀  \e[36m▐█   \e[39mN  E  R  V  E  S
  \e[34m█▌  \e[36m▀▀██▄▄  ▐█
  \e[34m███▌    \e[36m▀▀████\e[0m
  """
```

**Comment by fhunleth** [comment]
A little wider?

<img width="271" alt="image" src="https://user-images.githubusercontent.com/64669/137585835-fc5ae572-645a-4cd1-bc54-2a95f69ed493.png">

```
  @logo """
  \e[34m████▄▄     \e[36m▐███
  \e[34m█▌  ▀▀██▄▄   \e[36m▐█
  \e[34m█▌   \e[36m▄▄ \e[34m▀▀   \e[36m▐█   \e[39mN  E  R  V  E  S
  \e[34m█▌   \e[36m▀▀██▄▄  ▐█
  \e[34m███▌     \e[36m▀▀████\e[0m
  """
```

**Comment by fhunleth** [comment]
Longer lines?

<img width="262" alt="image" src="https://user-images.githubusercontent.com/64669/137585907-4cd72bb5-5808-47e6-96a1-55822eb24c50.png">


```
  @logo """
  \e[34m████▄▄     \e[36m▐███
  \e[34m█▌  ▀▀██▄▄   \e[36m▐█
  \e[34m█▌ \e[36m██▄▄ \e[34m▀▀██ \e[36m▐█   \e[39mN  E  R  V  E  S
  \e[34m█▌   \e[36m▀▀██▄▄  ▐█
  \e[34m███▌     \e[36m▀▀████\e[0m
  """
```

**Comment by fhunleth** [comment]
24-bit color. I'm not sure whether this will work on the terminal, though.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/64669/137588968-f4a829f0-1884-4f80-bed9-24b987113708.png">

```
  @logo """
  \e[38;2;63;100;125m████▄▄     \e[38;2;91;165;194m▐███
  \e[38;2;63;100;125m█▌  ▀▀██▄▄   \e[38;2;91;165;194m▐█
  \e[38;2;63;100;125m█▌ \e[38;2;91;165;194m██▄▄ \e[38;2;63;100;125m▀▀██ \e[38;2;91;165;194m▐█   \e[39mN  E  R  V  E  S
  \e[38;2;63;100;125m█▌   \e[38;2;91;165;194m▀▀██▄▄  ▐█
  \e[38;2;63;100;125m███▌     \e[38;2;91;165;194m▀▀████\e[0m
  """
```

Here's the original:
![image](https://user-images.githubusercontent.com/64669/137589009-629a2e4d-8867-42fb-b9c8-ed72a6e64f77.png)

**Comment by mnishiguchi** [comment]
The 8-bit color ANSI version gets distorted like the very beginning. The colors are good.

**Comment by fhunleth** [comment]
Argh. I don't even know how that's possible.

**Comment by mnishiguchi** [comment]
> Argh. I don't even know how that's possible.

Right it is strange. I'll double-check it.

**Comment by mnishiguchi** [comment]
My apologies. I just forgot to add my local `nerves_motd` in `mix.exs`.
The 8-bit color ANSI version is good in both shape and colors.

**Comment by fhunleth** [comment]
Yay!!!

Ok, is the 8-bit ANSI version of the thin N logo the favorite? Like it looks good to you in both the terminal and the RPi monitor? Should we ship that one?

**Comment by mnishiguchi** [comment]
Yeah [it](https://github.com/nerves-project/nerves_motd/issues/32#issuecomment-945016954) looks good and works well. I guess we are ready to ship it.
