### ISSUE TITLE
Add extra information fields to nerves_motd

### ISSUE THREAD

**Issue by layeddie** [nerves-project/nerves_motd#59]
I hope this is a good idea to add the following to Nerves_MOTD?
It would be helpful to trace back to the source folder on your local laptop and its always helpful to track back to the source code if its in git too. App_name label on the sdcard is useful too to find the correct sdcard when you are playing with different rpi's.
Be happy to collaborate if I can.
```
Src: /home/Projects/Nerves/app_name
Git: https://github.com/git_user_id/repo_name
Sdcard Label: app_name 
```
(This sdcard label is picked up from fwup.conf renamed Boot-A and Boot-B fields)

### Mix Firmware
Ideally this might mean adding options to mix firmware

`mix firmware --src appname --git https://github.com/git_user_id/repo_name`

### Current manual process to provide APPNAME boot label for Nerves Sdcard

These changes use your app_name to label the Sdcard.

It changes standard BOOT-A and BOOT-B label to APPNAME-A or APPNAME-B.

You need to make changes to config.exs, target.exs and add copies of fwup.conf and cmdline.txt to the config folder in your firmware project.

Copy fwup.conf to Your config/ Directory

Taken from instructions - Overwriting Files in the Boot Partition in https://hexdocs.pm/nerves/advanced-configuration.html

Locate the fwup.conf files available in your deps directory

```
cd app folder
find deps -name fwup.conf
```
Copy the one that matches your target to the config directory.

`cp deps/nerves_system_rpi0/fwup.conf config/`

Also copy cmdline.txt as you'll need it below.

`cp deps/nerves_system_rpi0/cmdline.txt config/`

edit the folowing 3 lines in config/fwup.conf and change BOOT-A and BOOT-B to nerves app_name.
(Is this name limited to 8 characters)
```
fat_setlabel(${BOOT_A_PART_OFFSET}, "APPNAME-A")
fat_setlabel(${BOOT_A_PART_OFFSET}, "APPNAME-A")
fat_setlabel(${BOOT_B_PART_OFFSET}, "APPNAME-B")
```

Changes to config.exs to add new path to config/fwup.conf

```
config :nerves, :firmware, 
  rootfs_overlay: "rootfs_overlay",
  fwup_conf: "config/fwup.conf"
```

Changes to target.exs

This line adds project name to iex prompt on rpi.

`config :iex, default_prompt: "%prefix(%counter)_app_name>"`

**Comment by fhunleth** [comment]
Hi @layeddie,

You're able to do this already by adding custom extra rows. See the `:extra_rows` parameter to `print/1` here: https://hexdocs.pm/nerves_motd/NervesMOTD.html#print/1. I think what we need are more examples to the `README.md` and API docs.

Here's how I use it in my projects.

In the `rootfs_overlay/etc/iex.exs`, add the `:extra_rows` option to the call to `print/1`:

```elixir
NervesMOTD.print(extra_rows: MyProject.additional_motd_rows())
```

Then in your project, add a function that gathers the data and returns it in a list of lists. Something like:

```elixir
  def additional_motd_rows() do
    [
      [{"Label", "value"}, {"Label2", "value2"}], 
      [{"Long label", "Lots of text"}]
    ]
  end
```

The fields that you're suggesting look useful for your use case. I don't think they're general enough to include by default here. I generally recommend writing blog posts to show off useful things like this. However, I'd definitely appreciate simple examples that I could include here for the docs. I'll take this as a note to see if there are useful examples that I can share here as well.

**Comment by layeddie** [comment]
Well blow me down with a feather duster! Built in already. Thanks for the example. I am working through your weather station project at the moment so that would be useful as an example.

**Comment by fhunleth** [comment]
I'm glad that you're making progress. I'm going to close this issue, since it's addressed.
