### ISSUE TITLE
Show mDNS name if available

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_motd#73]
It's nice to know what the mDNS name that devices respond to in addition to the hostname. This is usually what people want to use to connect to devices. It's also helpful to see if mDNS isn't configured right.

**Comment by mnishiguchi** [comment]
I started my research for this issue. Will this code do the job?

```elixir
with {:ok, hostname} <- :inet.gethostname(),
     hostname_dot_local = "#{hostname}.local",
     {:ok, {127, 0, 0, 1}} <- MdnsLite.gethostbyname(hostname_dot_local) do
  {:ok, hostname_dot_local}
else
  _ -> :error
end
```

**Comment by fhunleth** [comment]
Mdnslite is configurable so it depends on what the user set. I forgot how easy it was to get the advertised A records, but if it's not easy, I think Mdnslite should be improved.

**Comment by fhunleth** [comment]
I'm going to close this for now, since I'm not sure it's as useful as I thought it would be.
